from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


MigrationCategory = Literal["A_business", "B_operational_audit", "C_rebuildable", "D_runtime_temporary", "E_legacy"]


@dataclass(frozen=True)
class TableMigrationSpec:
    source_table: str
    target_table: str
    order: int | None
    primary_key: tuple[str, ...]
    dependencies: tuple[str, ...]
    columns: tuple[str, ...]
    category: MigrationCategory
    migrate: bool
    sequence_column: str | None
    json_columns: tuple[str, ...] = ()
    decimal_columns: tuple[str, ...] = ()
    boolean_columns: tuple[str, ...] = ()
    date_columns: tuple[str, ...] = ()
    timestamp_columns: tuple[str, ...] = ()
    blob_columns: tuple[str, ...] = ()
    storage_columns: tuple[str, ...] = ()
    verification: str = "count+primary_keys+canonical_row_hash+relations"
    exclusion_reason: str | None = None
    rebuild_procedure: str | None = None
    representative_fixture_required: bool = True
    legacy_source_optional: bool = False
    legacy_source_column_defaults: tuple[tuple[str, object], ...] = ()


MIGRATION_MANIFEST: tuple[TableMigrationSpec, ...] = (
    TableMigrationSpec(
        source_table='organizations',
        target_table='organizations',
        order=1,
        primary_key=('organization_id',),
        dependencies=(),
        columns=('organization_id', 'name', 'slug', 'module_shortcuts_json', 'communication_provider', 'communication_config_json', 'shared_note_text', 'shared_note_updated_at', 'shared_note_updated_by_user_id', 'telegram_chat_id', 'telegram_chat_name', 'email_inbox_address', 'email_allowed_sender', 'email_subject_keyword', 'email_integration_enabled', 'email_last_checked_at', 'email_last_check_status', 'email_last_connection_tested_at', 'email_last_connection_status', 'ksef_company_identifier', 'ksef_environment', 'ksef_integration_enabled', 'ksef_last_checked_at', 'ksef_last_check_status', 'ksef_last_connection_tested_at', 'ksef_last_connection_status', 'ksef_correction_delegate_user_id', 'ksef_correction_delegate_assigned_at', 'ksef_correction_delegate_expires_at', 'is_active', 'created_at', 'updated_at', 'work_item_sla_policy_json'),
        category='A_business',
        migrate=True,
        sequence_column='organization_id',
        json_columns=('module_shortcuts_json', 'communication_config_json', 'work_item_sla_policy_json'),
        decimal_columns=(),
        boolean_columns=('email_integration_enabled', 'ksef_integration_enabled', 'is_active'),
        date_columns=(),
        timestamp_columns=('shared_note_updated_at', 'email_last_checked_at', 'email_last_connection_tested_at', 'ksef_last_checked_at', 'ksef_last_connection_tested_at', 'ksef_correction_delegate_assigned_at', 'ksef_correction_delegate_expires_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='users',
        target_table='users',
        order=2,
        primary_key=('user_id',),
        dependencies=('organizations',),
        columns=('user_id', 'login', 'display_name', 'telegram_user_id', 'telegram_reminders_enabled', 'reminder_quiet_hours_start', 'reminder_quiet_hours_end', 'reminder_repeat_interval_minutes', 'organization_id', 'password_hash', 'password_salt', 'role', 'can_upload_knowledge', 'personal_note_text', 'personal_note_updated_at', 'workspace_state_json', 'workspace_state_updated_at', 'workspace_state_device_id', 'is_active', 'last_login_at', 'created_by_user_id', 'created_at', 'updated_at', 'browser_notifications_enabled'),
        category='A_business',
        migrate=True,
        sequence_column='user_id',
        json_columns=('workspace_state_json',),
        decimal_columns=(),
        boolean_columns=('telegram_reminders_enabled', 'can_upload_knowledge', 'is_active', 'browser_notifications_enabled'),
        date_columns=(),
        timestamp_columns=('personal_note_updated_at', 'workspace_state_updated_at', 'last_login_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='organization_memberships',
        target_table='organization_memberships',
        order=3,
        primary_key=('organization_membership_id',),
        dependencies=('organizations', 'users'),
        columns=('organization_membership_id', 'user_id', 'organization_id', 'role', 'membership_status', 'is_primary', 'granted_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='organization_membership_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_primary',),
        date_columns=(),
        timestamp_columns=('granted_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='organization_modules',
        target_table='organization_modules',
        order=4,
        primary_key=('organization_module_id',),
        dependencies=('organizations', 'users'),
        columns=('organization_module_id', 'organization_id', 'module_code', 'enabled_at', 'enabled_by_user_id'),
        category='A_business',
        migrate=True,
        sequence_column='organization_module_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('enabled_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='user_capabilities',
        target_table='user_capabilities',
        order=5,
        primary_key=('user_capability_id',),
        dependencies=('users',),
        columns=('user_capability_id', 'user_id', 'capability_code', 'granted_at'),
        category='A_business',
        migrate=True,
        sequence_column='user_capability_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('granted_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='system_settings',
        target_table='system_settings',
        order=6,
        primary_key=('system_setting_id',),
        dependencies=('users',),
        columns=('system_setting_id', 'setting_key', 'setting_value_text', 'updated_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='system_setting_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='user_calendars',
        target_table='user_calendars',
        order=7,
        primary_key=('user_calendar_id',),
        dependencies=('organizations', 'users'),
        columns=('user_calendar_id', 'owner_user_id', 'provider', 'display_name', 'calendar_kind', 'linked_organization_id', 'default_duration_minutes', 'description', 'sync_token', 'external_calendar_id', 'external_calendar_name', 'external_calendar_timezone', 'is_active', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='user_calendar_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_active',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='user_google_calendar_connections',
        target_table='user_google_calendar_connections',
        order=8,
        primary_key=('user_google_calendar_connection_id',),
        dependencies=('users',),
        columns=('user_google_calendar_connection_id', 'user_id', 'google_email', 'access_token', 'refresh_token', 'token_expires_at', 'scope', 'employee_visibility_confirmed', 'employee_confirmation_at', 'approval_status', 'approved_by_user_id', 'approved_at', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='user_google_calendar_connection_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('employee_visibility_confirmed',),
        date_columns=(),
        timestamp_columns=('token_expires_at', 'employee_confirmation_at', 'approved_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='user_calendar_assignments',
        target_table='user_calendar_assignments',
        order=9,
        primary_key=('user_calendar_assignment_id',),
        dependencies=('user_calendars', 'users'),
        columns=('user_calendar_assignment_id', 'user_id', 'user_calendar_id', 'assigned_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='user_calendar_assignment_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='system_email_google_connections',
        target_table='system_email_google_connections',
        order=10,
        primary_key=('system_email_google_connection_id',),
        dependencies=('users',),
        columns=('system_email_google_connection_id', 'provider', 'google_email', 'access_token', 'refresh_token', 'token_expires_at', 'scope', 'created_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='system_email_google_connection_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('token_expires_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='tasks',
        target_table='tasks',
        order=11,
        primary_key=('task_id',),
        dependencies=('organizations', 'user_calendars', 'users'),
        columns=('task_id', 'organization_id', 'task_type', 'visibility_scope', 'owner_user_id', 'title', 'description', 'status', 'priority', 'due_at', 'remind_at', 'recurrence_pattern', 'recurrence_interval', 'recurrence_weekdays', 'recurrence_end_at', 'recurrence_series_id', 'recurrence_parent_task_id', 'reminder_sent_at', 'reminder_last_attempt_at', 'reminder_last_error', 'assigned_user_id', 'calendar_id', 'calendar_duration_minutes', 'external_calendar_event_id', 'external_calendar_event_url', 'external_calendar_synced_at', 'external_calendar_sync_error', 'external_calendar_sync_state', 'external_calendar_sync_message', 'external_calendar_last_checked_at', 'external_calendar_last_check_error', 'external_calendar_remote_updated_at', 'external_calendar_remote_etag', 'external_calendar_last_sync_source', 'created_by_user_id', 'completed_at', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_id',
        json_columns=('recurrence_weekdays',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('due_at', 'remind_at', 'recurrence_end_at', 'reminder_sent_at', 'reminder_last_attempt_at', 'external_calendar_synced_at', 'external_calendar_last_checked_at', 'external_calendar_remote_updated_at', 'completed_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_visibility_users',
        target_table='task_visibility_users',
        order=12,
        primary_key=('task_visibility_user_id',),
        dependencies=('organizations', 'tasks', 'users'),
        columns=('task_visibility_user_id', 'task_id', 'organization_id', 'user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_visibility_user_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_links',
        target_table='task_links',
        order=13,
        primary_key=('task_link_id',),
        dependencies=('organizations', 'tasks', 'users'),
        columns=('task_link_id', 'task_id', 'organization_id', 'entity_type', 'entity_id', 'created_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_link_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_notes',
        target_table='task_notes',
        order=14,
        primary_key=('task_note_id',),
        dependencies=('organizations', 'tasks', 'users'),
        columns=('task_note_id', 'task_id', 'organization_id', 'parent_note_id', 'note_kind', 'note_text', 'mentioned_user_ids', 'mentioned_user_names', 'created_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_note_id',
        json_columns=('mentioned_user_ids',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_checklist_items',
        target_table='task_checklist_items',
        order=15,
        primary_key=('task_checklist_item_id',),
        dependencies=('organizations', 'tasks', 'users'),
        columns=('task_checklist_item_id', 'task_id', 'organization_id', 'item_text', 'item_order', 'is_completed', 'completed_at', 'completed_by_user_id', 'created_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_checklist_item_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_completed',),
        date_columns=(),
        timestamp_columns=('completed_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_templates',
        target_table='task_templates',
        order=16,
        primary_key=('task_template_id',),
        dependencies=('organizations', 'users'),
        columns=('task_template_id', 'organization_id', 'template_name', 'template_description', 'task_type', 'priority', 'visibility_scope', 'due_offset_minutes', 'reminder_offset_minutes', 'recurrence_pattern', 'recurrence_interval', 'recurrence_weekdays', 'recurrence_end_offset_minutes', 'calendar_duration_minutes', 'checklist_json', 'is_active', 'created_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_template_id',
        json_columns=('recurrence_weekdays', 'checklist_json'),
        decimal_columns=(),
        boolean_columns=('is_active',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='approval_requests',
        target_table='approval_requests',
        order=17,
        primary_key=('approval_request_id',),
        dependencies=('organizations', 'users'),
        columns=('approval_request_id', 'organization_id', 'entity_type', 'entity_id', 'title', 'description', 'status', 'requested_by_user_id', 'requested_user_id', 'approve_status', 'reject_status', 'metadata_json', 'requested_at', 'decided_by_user_id', 'decided_at', 'decision_reason', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='approval_request_id',
        json_columns=('metadata_json',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('requested_at', 'decided_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_attachments',
        target_table='task_attachments',
        order=18,
        primary_key=('task_attachment_id',),
        dependencies=('organizations', 'tasks', 'users'),
        columns=('task_attachment_id', 'task_id', 'organization_id', 'file_name', 'mime_type', 'file_size', 'file_link', 'file_storage_key', 'storage_backend', 'uploaded_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='task_attachment_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=('file_link', 'file_storage_key'),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_history',
        target_table='task_history',
        order=19,
        primary_key=('task_history_id',),
        dependencies=('organizations', 'tasks'),
        columns=('task_history_id', 'task_id', 'organization_id', 'action_type', 'actor', 'message', 'details', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='task_history_id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='work_items',
        target_table='work_items',
        order=20,
        primary_key=('work_item_id',),
        dependencies=('organizations', 'users'),
        columns=('work_item_id', 'organization_id', 'source_type', 'source_id', 'title', 'description', 'status', 'priority_level', 'priority_score', 'assigned_user_id', 'created_by_user_id', 'updated_by_user_id', 'due_at', 'sla_deadline_at', 'sla_warning_minutes', 'sla_warning_at', 'sla_stage', 'reminder_sent_at', 'escalation_sent_at', 'resolved_at', 'last_sla_transition_at', 'metadata_json', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='work_item_id',
        json_columns=('metadata_json',),
        decimal_columns=('priority_score',),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('due_at', 'sla_deadline_at', 'sla_warning_at', 'reminder_sent_at', 'escalation_sent_at', 'resolved_at', 'last_sla_transition_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='work_item_history',
        target_table='work_item_history',
        order=21,
        primary_key=('work_item_history_id',),
        dependencies=('organizations', 'work_items'),
        columns=('work_item_history_id', 'work_item_id', 'organization_id', 'action_type', 'actor', 'message', 'details', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='work_item_history_id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='contractors',
        target_table='contractors',
        order=22,
        primary_key=('contractor_id',),
        dependencies=('organizations',),
        columns=('contractor_id', 'organization_id', 'name', 'nip', 'email', 'phone', 'is_new', 'last_invoice_date', 'last_invoice_number', 'invoice_count', 'notes', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='contractor_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_new',),
        date_columns=('last_invoice_date',),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='contractor_notes',
        target_table='contractor_notes',
        order=23,
        primary_key=('contractor_note_id',),
        dependencies=('contractors', 'organizations', 'users'),
        columns=('contractor_note_id', 'organization_id', 'contractor_id', 'author_user_id', 'note_text', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='contractor_note_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='invoices',
        target_table='invoices',
        order=24,
        primary_key=('id',),
        dependencies=('contractors', 'organizations', 'users'),
        columns=('id', 'organization_id', 'incoming_date', 'source', 'file_name', 'document_type', 'invoice_number', 'ksef_number', 'issuer_nip', 'issuer_name', 'issue_date', 'sale_date', 'gross_amount', 'currency', 'status', 'duplicate_type', 'flag_reason', 'contractor_id', 'file_link', 'file_storage_key', 'ocr_link', 'ocr_storage_key', 'storage_backend', 'source_external_id', 'source_sender_name', 'source_sender_id', 'source_metadata', 'invoice_hash', 'ocr_raw_text', 'ocr_confidence', 'assigned_user_id', 'notes', 'created_at', 'updated_at', 'authoritative_source', 'workflow_state', 'ready_for_handoff_at', 'ready_for_handoff_by_user_id', 'handoff_target', 'handoff_note', 'handed_off_at', 'handed_off_by_user_id', 'closed_at', 'closed_by_user_id', 'closed_reason', 'reopened_at', 'reopened_by_user_id', 'reopen_reason'),
        category='A_business',
        migrate=True,
        sequence_column='id',
        json_columns=(),
        decimal_columns=('gross_amount', 'ocr_confidence'),
        boolean_columns=(),
        date_columns=('incoming_date', 'issue_date', 'sale_date'),
        timestamp_columns=('created_at', 'updated_at', 'ready_for_handoff_at', 'handed_off_at', 'closed_at', 'reopened_at'),
        blob_columns=(),
        storage_columns=('file_link', 'file_storage_key', 'ocr_storage_key'),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='invoice_relations',
        target_table='invoice_relations',
        order=25,
        primary_key=('id',),
        dependencies=('invoices',),
        columns=('id', 'invoice_id', 'related_invoice_id', 'relation_type', 'reason', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='invoice_comments',
        target_table='invoice_comments',
        order=26,
        primary_key=('invoice_comment_id',),
        dependencies=('invoices', 'organizations', 'users'),
        columns=('invoice_comment_id', 'invoice_id', 'organization_id', 'parent_comment_id', 'note_text', 'created_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='invoice_comment_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='invoice_handoff_batches',
        target_table='invoice_handoff_batches',
        order=27,
        primary_key=('invoice_handoff_batch_id',),
        dependencies=('organizations', 'users'),
        columns=('invoice_handoff_batch_id', 'organization_id', 'batch_number', 'handoff_target', 'note', 'status', 'invoice_count', 'created_by_user_id', 'created_at', 'exported_at', 'exported_by_user_id', 'export_format', 'export_metadata', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='invoice_handoff_batch_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at', 'exported_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='invoice_handoff_batch_items',
        target_table='invoice_handoff_batch_items',
        order=28,
        primary_key=('invoice_handoff_batch_item_id',),
        dependencies=('invoice_handoff_batches', 'invoices'),
        columns=('invoice_handoff_batch_item_id', 'invoice_handoff_batch_id', 'invoice_id', 'organization_id', 'workflow_state_snapshot', 'status_snapshot', 'source_snapshot', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='invoice_handoff_batch_item_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='invoice_ksef_field_overrides',
        target_table='invoice_ksef_field_overrides',
        order=29,
        primary_key=('invoice_ksef_field_override_id',),
        dependencies=('approval_requests', 'invoices', 'organizations', 'users'),
        columns=('invoice_ksef_field_override_id', 'organization_id', 'invoice_id', 'approval_request_id', 'field_name', 'source_value', 'local_value', 'status', 'requested_by_user_id', 'approved_by_user_id', 'rejected_by_user_id', 'request_reason', 'decision_reason', 'created_at', 'updated_at', 'approved_at', 'rejected_at'),
        category='A_business',
        migrate=True,
        sequence_column='invoice_ksef_field_override_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at', 'approved_at', 'rejected_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_schools',
        target_table='billing_schools',
        order=30,
        primary_key=('billing_school_id',),
        dependencies=('organizations',),
        columns=('billing_school_id', 'organization_id', 'full_name', 'short_name', 'city', 'notes', 'is_active', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_school_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_active',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_models',
        target_table='billing_models',
        order=31,
        primary_key=('billing_model_id',),
        dependencies=('organizations',),
        columns=('billing_model_id', 'organization_id', 'name', 'profile_type', 'school_year', 'lesson_day', 'settlement_mode', 'monthly_rate_amount', 'semester_rate_amount', 'sibling_discount_amount', 'large_family_discount_amount', 'intro_free_lessons_count', 'contract_required', 'notes', 'is_active', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_model_id',
        json_columns=(),
        decimal_columns=('monthly_rate_amount', 'semester_rate_amount', 'sibling_discount_amount', 'large_family_discount_amount'),
        boolean_columns=('contract_required', 'is_active'),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_payers',
        target_table='billing_payers',
        order=32,
        primary_key=('billing_payer_id',),
        dependencies=('organizations',),
        columns=('billing_payer_id', 'organization_id', 'display_name', 'contact_phone', 'payment_identifier', 'has_large_family_card', 'email', 'notes', 'is_active', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_payer_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('has_large_family_card', 'is_active'),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_students',
        target_table='billing_students',
        order=33,
        primary_key=('billing_student_id',),
        dependencies=('billing_models', 'billing_payers', 'billing_schools', 'organizations'),
        columns=('billing_student_id', 'organization_id', 'billing_payer_id', 'billing_school_id', 'billing_model_id', 'full_name', 'lesson_day', 'family_billing_order', 'group_name', 'notes', 'is_active', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_student_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_active',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_charge_batches',
        target_table='billing_charge_batches',
        order=34,
        primary_key=('billing_charge_batch_id',),
        dependencies=('billing_models', 'organizations', 'users'),
        columns=('billing_charge_batch_id', 'organization_id', 'billing_model_id', 'school_year', 'period_type', 'period_label', 'due_date', 'lesson_count', 'generated_by_user_id', 'notes', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_charge_batch_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=('due_date',),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_charges',
        target_table='billing_charges',
        order=35,
        primary_key=('billing_charge_id',),
        dependencies=('billing_charge_batches', 'billing_models', 'billing_payers', 'billing_students', 'organizations'),
        columns=('billing_charge_id', 'organization_id', 'billing_charge_batch_id', 'billing_model_id', 'billing_student_id', 'billing_payer_id', 'school_year', 'period_label', 'due_date', 'lesson_count', 'unit_rate_amount', 'base_amount', 'intro_free_discount_amount', 'sibling_discount_amount', 'large_family_discount_amount', 'total_amount', 'status', 'notes', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_charge_id',
        json_columns=(),
        decimal_columns=('unit_rate_amount', 'base_amount', 'intro_free_discount_amount', 'sibling_discount_amount', 'large_family_discount_amount', 'total_amount'),
        boolean_columns=(),
        date_columns=('due_date',),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_student_charge_state',
        target_table='billing_student_charge_state',
        order=36,
        primary_key=('billing_student_charge_state_id',),
        dependencies=('billing_students', 'organizations'),
        columns=('billing_student_charge_state_id', 'organization_id', 'billing_student_id', 'school_year', 'intro_free_lessons_remaining', 'sibling_discount_remaining_amount', 'sibling_discount_initialized', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_student_charge_state_id',
        json_columns=(),
        decimal_columns=('sibling_discount_remaining_amount',),
        boolean_columns=('sibling_discount_initialized',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_payer_charge_state',
        target_table='billing_payer_charge_state',
        order=37,
        primary_key=('billing_payer_charge_state_id',),
        dependencies=('billing_payers', 'organizations'),
        columns=('billing_payer_charge_state_id', 'organization_id', 'billing_payer_id', 'school_year', 'large_family_discount_remaining_amount', 'large_family_discount_initialized', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_payer_charge_state_id',
        json_columns=(),
        decimal_columns=('large_family_discount_remaining_amount',),
        boolean_columns=('large_family_discount_initialized',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_bank_accounts',
        target_table='billing_bank_accounts',
        order=38,
        primary_key=('billing_bank_account_id',),
        dependencies=('organizations',),
        columns=('billing_bank_account_id', 'organization_id', 'account_name', 'bank_name', 'iban', 'currency', 'is_active', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_bank_account_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=('is_active',),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_statement_imports',
        target_table='billing_statement_imports',
        order=39,
        primary_key=('billing_statement_import_id',),
        dependencies=('billing_bank_accounts', 'organizations', 'users'),
        columns=('billing_statement_import_id', 'organization_id', 'billing_bank_account_id', 'source_type', 'source_file_name', 'imported_by_user_id', 'imported_at', 'row_count', 'imported_transaction_count', 'skipped_transaction_count', 'status', 'notes', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_statement_import_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('imported_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_transactions',
        target_table='billing_transactions',
        order=40,
        primary_key=('billing_transaction_id',),
        dependencies=('billing_bank_accounts', 'billing_statement_imports', 'organizations'),
        columns=('billing_transaction_id', 'organization_id', 'billing_bank_account_id', 'billing_statement_import_id', 'booking_date', 'value_date', 'amount', 'currency', 'direction', 'counterparty_name', 'counterparty_account', 'title', 'reference', 'raw_data', 'transaction_hash', 'matched_status', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_transaction_id',
        json_columns=('raw_data',),
        decimal_columns=('amount',),
        boolean_columns=(),
        date_columns=('booking_date', 'value_date'),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_payment_review_events',
        target_table='billing_payment_review_events',
        order=41,
        primary_key=('billing_payment_review_event_id',),
        dependencies=('billing_transactions', 'organizations', 'users'),
        columns=('billing_payment_review_event_id', 'organization_id', 'billing_transaction_id', 'status', 'note_text', 'created_by_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='billing_payment_review_event_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_work_queue_events',
        target_table='billing_work_queue_events',
        order=42,
        primary_key=('billing_work_queue_event_id',),
        dependencies=('organizations', 'users'),
        columns=('billing_work_queue_event_id', 'organization_id', 'issue_key', 'issue_type', 'target_type', 'target_id', 'action', 'note_text', 'created_by_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='billing_work_queue_event_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_contact_events',
        target_table='billing_contact_events',
        order=43,
        primary_key=('billing_contact_event_id',),
        dependencies=('billing_payers', 'billing_transactions', 'organizations', 'users'),
        columns=('billing_contact_event_id', 'organization_id', 'billing_payer_id', 'related_payment_id', 'related_issue_key', 'channel', 'contact_action', 'message_text', 'note_text', 'created_by_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='billing_contact_event_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_next_step_events',
        target_table='billing_next_step_events',
        order=44,
        primary_key=('billing_next_step_event_id',),
        dependencies=('organizations', 'users'),
        columns=('billing_next_step_event_id', 'parent_event_id', 'organization_id', 'target_type', 'target_id', 'related_issue_key', 'step_type', 'event_action', 'title', 'note_text', 'planned_for', 'created_by_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='billing_next_step_event_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=('planned_for',),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
        legacy_source_column_defaults=(('parent_event_id', None),),
    ),
    TableMigrationSpec(
        source_table='billing_payment_matches',
        target_table='billing_payment_matches',
        order=45,
        primary_key=('billing_payment_match_id',),
        dependencies=('billing_charges', 'billing_payers', 'billing_transactions', 'organizations', 'users'),
        columns=('billing_payment_match_id', 'organization_id', 'billing_transaction_id', 'billing_payer_id', 'billing_charge_id', 'matched_amount', 'match_status', 'match_reason', 'matched_by_user_id', 'matched_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_payment_match_id',
        json_columns=(),
        decimal_columns=('matched_amount',),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('matched_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_payer_ledger_entries',
        target_table='billing_payer_ledger_entries',
        order=46,
        primary_key=('billing_payer_ledger_entry_id',),
        dependencies=('billing_charges', 'billing_payers', 'billing_transactions', 'organizations', 'users'),
        columns=('billing_payer_ledger_entry_id', 'organization_id', 'billing_payer_id', 'billing_charge_id', 'billing_transaction_id', 'entry_kind', 'amount_delta', 'balance_after', 'note', 'created_by_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='billing_payer_ledger_entry_id',
        json_columns=(),
        decimal_columns=('amount_delta', 'balance_after'),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='billing_notes',
        target_table='billing_notes',
        order=47,
        primary_key=('billing_note_id',),
        dependencies=('billing_payers', 'organizations', 'users'),
        columns=('billing_note_id', 'organization_id', 'billing_payer_id', 'author_user_id', 'note_type', 'note_text', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='billing_note_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='knowledge_documents',
        target_table='knowledge_documents',
        order=48,
        primary_key=('knowledge_document_id',),
        dependencies=('organizations', 'users'),
        columns=('knowledge_document_id', 'organization_id', 'title', 'file_name', 'mime_type', 'file_link', 'file_storage_key', 'content_text', 'content_hash', 'char_count', 'source_type', 'library_path', 'is_downloadable', 'use_in_assistant', 'business_status', 'business_status_before_archive', 'owner_user_id', 'reviewer_user_id', 'approver_user_id', 'created_by_user_id', 'created_at', 'updated_at', 'processing_status', 'processing_error', 'current_version_number', 'official_version_number', 'official_version_marked_at', 'official_version_marked_by_user_id', 'last_processed_at', 'processing_started_at', 'lifecycle_status', 'archived_at', 'archived_by_user_id', 'deleted_at', 'deleted_by_user_id', 'duplicate_status', 'duplicate_of_document_id', 'duplicate_score', 'duplicate_reason', 'last_seen_in_folder_at'),
        category='A_business',
        migrate=True,
        sequence_column='knowledge_document_id',
        json_columns=(),
        decimal_columns=('duplicate_score',),
        boolean_columns=('is_downloadable', 'use_in_assistant'),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at', 'official_version_marked_at', 'last_processed_at', 'processing_started_at', 'archived_at', 'deleted_at', 'last_seen_in_folder_at'),
        blob_columns=(),
        storage_columns=('file_link', 'file_storage_key', 'library_path'),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='knowledge_document_versions',
        target_table='knowledge_document_versions',
        order=49,
        primary_key=('knowledge_document_version_id',),
        dependencies=('knowledge_documents', 'organizations', 'users'),
        columns=('knowledge_document_version_id', 'knowledge_document_id', 'organization_id', 'version_number', 'title', 'file_name', 'mime_type', 'file_link', 'file_storage_key', 'content_text', 'content_hash', 'char_count', 'source_type', 'created_by_user_id', 'extraction_method', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='knowledge_document_version_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=('file_link', 'file_storage_key'),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='knowledge_processing_jobs',
        target_table='knowledge_processing_jobs',
        order=50,
        primary_key=('knowledge_processing_job_id',),
        dependencies=('knowledge_documents', 'organizations', 'users'),
        columns=('knowledge_processing_job_id', 'organization_id', 'knowledge_document_id', 'job_type', 'status', 'source_storage_key', 'source_file_name', 'source_mime_type', 'source_type', 'source_content_hash', 'supplemental_text', 'error_message', 'attempts', 'max_attempts', 'created_by_user_id', 'started_at', 'finished_at', 'created_at', 'updated_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='knowledge_processing_job_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('started_at', 'finished_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=('source_storage_key',),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='knowledge_folder_watchers',
        target_table='knowledge_folder_watchers',
        order=51,
        primary_key=('knowledge_folder_watcher_id',),
        dependencies=('organizations',),
        columns=('knowledge_folder_watcher_id', 'organization_id', 'watch_mode', 'last_scan_started_at', 'last_scan_completed_at', 'last_scan_status', 'last_actor', 'last_error', 'queued_new', 'queued_updates', 'unchanged_count', 'skipped_count', 'duplicate_count', 'similar_count', 'updated_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='knowledge_folder_watcher_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('last_scan_started_at', 'last_scan_completed_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='knowledge_document_comments',
        target_table='knowledge_document_comments',
        order=52,
        primary_key=('knowledge_document_comment_id',),
        dependencies=('knowledge_document_versions', 'knowledge_documents', 'organizations', 'users'),
        columns=('knowledge_document_comment_id', 'knowledge_document_id', 'organization_id', 'knowledge_document_version_id', 'version_number', 'parent_comment_id', 'annotation_kind', 'anchor_label', 'anchor_excerpt', 'note_text', 'created_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='knowledge_document_comment_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='intake_forms',
        target_table='intake_forms',
        order=53,
        primary_key=('intake_form_id',),
        dependencies=('organizations', 'users'),
        columns=('intake_form_id', 'organization_id', 'form_name', 'form_slug', 'description', 'field_schema_json', 'is_public', 'allow_attachments', 'default_priority', 'default_assigned_user_id', 'public_token', 'created_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='intake_form_id',
        json_columns=('field_schema_json',),
        decimal_columns=(),
        boolean_columns=('is_public', 'allow_attachments'),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='intake_items',
        target_table='intake_items',
        order=54,
        primary_key=('intake_item_id',),
        dependencies=('intake_forms', 'invoices', 'organizations', 'tasks', 'users'),
        columns=('intake_item_id', 'organization_id', 'intake_form_id', 'source_kind', 'status', 'priority', 'title', 'description', 'requester_name', 'requester_email', 'source_reference', 'due_at', 'metadata_json', 'assigned_user_id', 'linked_task_id', 'linked_invoice_id', 'created_by_user_id', 'last_activity_at', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='intake_item_id',
        json_columns=('metadata_json',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('due_at', 'last_activity_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='intake_item_comments',
        target_table='intake_item_comments',
        order=55,
        primary_key=('intake_item_comment_id',),
        dependencies=('intake_items', 'organizations', 'users'),
        columns=('intake_item_comment_id', 'intake_item_id', 'organization_id', 'parent_comment_id', 'note_text', 'mentioned_user_ids', 'mentioned_user_names', 'created_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='intake_item_comment_id',
        json_columns=('mentioned_user_ids',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='intake_item_history',
        target_table='intake_item_history',
        order=56,
        primary_key=('intake_item_history_id',),
        dependencies=('intake_items', 'organizations'),
        columns=('intake_item_history_id', 'intake_item_id', 'organization_id', 'action_type', 'actor', 'message', 'details', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='intake_item_history_id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='entity_attachments',
        target_table='entity_attachments',
        order=57,
        primary_key=('entity_attachment_id',),
        dependencies=('organizations', 'users'),
        columns=('entity_attachment_id', 'organization_id', 'entity_type', 'entity_id', 'file_name', 'mime_type', 'file_size', 'file_link', 'file_storage_key', 'storage_backend', 'uploaded_by_user_id', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='entity_attachment_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=('file_link', 'file_storage_key'),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='saved_views',
        target_table='saved_views',
        order=58,
        primary_key=('saved_view_id',),
        dependencies=('organizations', 'users'),
        columns=('saved_view_id', 'organization_id', 'module_key', 'view_slug', 'view_name', 'description', 'view_state_json', 'is_shared', 'is_default', 'created_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='saved_view_id',
        json_columns=('view_state_json',),
        decimal_columns=(),
        boolean_columns=('is_shared', 'is_default'),
        date_columns=(),
        timestamp_columns=('created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='automation_rules',
        target_table='automation_rules',
        order=59,
        primary_key=('automation_rule_id',),
        dependencies=('organizations', 'users'),
        columns=('automation_rule_id', 'organization_id', 'rule_slug', 'rule_name', 'description', 'trigger_event_type', 'conditions_json', 'actions_json', 'is_active', 'last_processed_event_log_id', 'last_run_at', 'last_result', 'execution_count', 'created_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='automation_rule_id',
        json_columns=('conditions_json', 'actions_json'),
        decimal_columns=(),
        boolean_columns=('is_active',),
        date_columns=(),
        timestamp_columns=('last_run_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='organization_whiteboard_events',
        target_table='organization_whiteboard_events',
        order=60,
        primary_key=('whiteboard_event_id',),
        dependencies=('organizations', 'users'),
        columns=('whiteboard_event_id', 'organization_id', 'event_type', 'payload_json', 'created_by_user_id', 'actor_label', 'created_at'),
        category='A_business',
        migrate=True,
        sequence_column='whiteboard_event_id',
        json_columns=('payload_json',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='event_logs',
        target_table='event_logs',
        order=61,
        primary_key=('id',),
        dependencies=('invoices', 'organizations'),
        columns=('id', 'organization_id', 'event_time', 'event_type', 'invoice_id', 'source', 'status_before', 'status_after', 'decision_reason', 'actor', 'details'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('event_time',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='automation_executions',
        target_table='automation_executions',
        order=62,
        primary_key=('automation_execution_id',),
        dependencies=('automation_rules', 'event_logs', 'organizations'),
        columns=('automation_execution_id', 'automation_rule_id', 'organization_id', 'event_log_id', 'trigger_event_type', 'execution_status', 'input_json', 'result_json', 'error_message', 'executed_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='automation_execution_id',
        json_columns=('input_json', 'result_json'),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('executed_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='email_import_runs',
        target_table='email_import_runs',
        order=63,
        primary_key=('email_import_run_id',),
        dependencies=('organizations',),
        columns=('email_import_run_id', 'organization_id', 'mailbox_address', 'inbox_address', 'trigger_mode', 'actor', 'routing_mode', 'started_at', 'finished_at', 'status', 'checked_message_count', 'matched_message_count', 'matched_attachment_count', 'imported_invoice_count', 'skipped_existing_count', 'skipped_error_count', 'summary_message', 'details'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='email_import_run_id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('started_at', 'finished_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='email_import_items',
        target_table='email_import_items',
        order=64,
        primary_key=('email_import_item_id',),
        dependencies=('email_import_runs', 'invoices', 'organizations'),
        columns=('email_import_item_id', 'email_import_run_id', 'organization_id', 'imap_uid', 'message_id', 'sender_email', 'subject', 'recipients', 'matched_recipient', 'attachment_name', 'attachment_type', 'attachment_index', 'source_external_id', 'item_status', 'invoice_id', 'reason', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='email_import_item_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='ksef_import_runs',
        target_table='ksef_import_runs',
        order=65,
        primary_key=('ksef_import_run_id',),
        dependencies=('organizations',),
        columns=('ksef_import_run_id', 'organization_id', 'company_identifier', 'environment', 'trigger_mode', 'actor', 'started_at', 'finished_at', 'status', 'checked_document_count', 'imported_invoice_count', 'skipped_existing_count', 'skipped_error_count', 'summary_message', 'details'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='ksef_import_run_id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('started_at', 'finished_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='ksef_import_items',
        target_table='ksef_import_items',
        order=66,
        primary_key=('ksef_import_item_id',),
        dependencies=('invoices', 'ksef_import_runs', 'organizations'),
        columns=('ksef_import_item_id', 'ksef_import_run_id', 'organization_id', 'source_external_id', 'ksef_number', 'invoice_number', 'issuer_nip', 'issue_date', 'item_status', 'invoice_id', 'reason', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='ksef_import_item_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=('issue_date',),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_reminder_outbox',
        target_table='task_reminder_outbox',
        order=67,
        primary_key=('task_reminder_outbox_id',),
        dependencies=('organizations', 'tasks', 'users'),
        columns=('task_reminder_outbox_id', 'organization_id', 'task_id', 'delivery_channel', 'delivery_key', 'delivery_anchor_at', 'recipient_user_id', 'recipient_telegram_user_id', 'available_at', 'status', 'retryable', 'attempt_count', 'claimed_at', 'claimed_by', 'last_attempt_at', 'last_error', 'sent_at', 'payload', 'created_at', 'updated_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='task_reminder_outbox_id',
        json_columns=('payload',),
        decimal_columns=(),
        boolean_columns=('retryable',),
        date_columns=(),
        timestamp_columns=('delivery_anchor_at', 'available_at', 'claimed_at', 'last_attempt_at', 'sent_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='task_reminder_outbox_attempts',
        target_table='task_reminder_outbox_attempts',
        order=68,
        primary_key=('task_reminder_outbox_attempt_id',),
        dependencies=('organizations', 'task_reminder_outbox', 'tasks'),
        columns=('task_reminder_outbox_attempt_id', 'task_reminder_outbox_id', 'organization_id', 'task_id', 'delivery_channel', 'attempt_no', 'outcome', 'attempted_at', 'worker_name', 'error_message', 'details', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='task_reminder_outbox_attempt_id',
        json_columns=('details',),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('attempted_at', 'created_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='internal_notifications',
        target_table='internal_notifications',
        order=69,
        primary_key=('internal_notification_id',),
        dependencies=('billing_next_step_events', 'organizations', 'users'),
        columns=('internal_notification_id', 'organization_id', 'recipient_user_id', 'source_type', 'source_event_id', 'reason_code', 'detected_on', 'planned_for', 'title_snapshot', 'target_type', 'target_id', 'related_issue_key', 'target_label_snapshot', 'internal_link_snapshot', 'dedupe_key', 'created_by_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='internal_notification_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=('planned_for',),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
        legacy_source_optional=True,
    ),
    TableMigrationSpec(
        source_table='internal_notification_state_events',
        target_table='internal_notification_state_events',
        order=70,
        primary_key=('internal_notification_state_event_id',),
        dependencies=('internal_notifications', 'organizations', 'users'),
        columns=('internal_notification_state_event_id', 'notification_id', 'organization_id', 'recipient_user_id', 'action', 'actor_user_id', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='internal_notification_state_event_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
        legacy_source_optional=True,
    ),
    TableMigrationSpec(
        source_table='internal_notification_schedules',
        target_table='internal_notification_schedules',
        order=71,
        primary_key=('internal_notification_schedule_id',),
        dependencies=('organizations', 'users'),
        columns=('internal_notification_schedule_id', 'organization_id', 'recipient_user_id', 'source_type', 'enabled', 'cadence', 'timezone_name', 'local_time', 'next_run_at_utc', 'created_by_user_id', 'updated_by_user_id', 'created_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='internal_notification_schedule_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('next_run_at_utc', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
        legacy_source_optional=True,
    ),
    TableMigrationSpec(
        source_table='internal_notification_schedule_runs',
        target_table='internal_notification_schedule_runs',
        order=72,
        primary_key=('internal_notification_schedule_run_id',),
        dependencies=('internal_notification_schedules', 'organizations', 'users'),
        columns=('internal_notification_schedule_run_id', 'schedule_id', 'organization_id', 'recipient_user_id', 'source_type', 'scheduled_local_date', 'as_of_date', 'scheduled_for_utc', 'status', 'attempt_count', 'lease_token', 'lease_expires_at_utc', 'next_attempt_at_utc', 'candidates_count', 'created_count', 'existing_count', 'error_code', 'error_summary', 'started_at', 'finished_at', 'created_at'),
        category='B_operational_audit',
        migrate=True,
        sequence_column='internal_notification_schedule_run_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=('scheduled_local_date', 'as_of_date'),
        timestamp_columns=('lease_expires_at_utc', 'next_attempt_at_utc', 'started_at', 'finished_at', 'created_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
        legacy_source_optional=True,
    ),
    TableMigrationSpec(
        source_table='user_module_inbox_state',
        target_table='user_module_inbox_state',
        order=73,
        primary_key=('user_module_inbox_state_id',),
        dependencies=('event_logs', 'organizations', 'users'),
        columns=('user_module_inbox_state_id', 'user_id', 'organization_id', 'module_key', 'last_seen_event_id', 'last_seen_at', 'updated_at'),
        category='A_business',
        migrate=True,
        sequence_column='user_module_inbox_state_id',
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('last_seen_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason=None,
        rebuild_procedure=None,
        representative_fixture_required=True,
    ),
    TableMigrationSpec(
        source_table='casi_schema_metadata',
        target_table='casi_schema_metadata',
        order=None,
        primary_key=('schema_key',),
        dependencies=(),
        columns=('schema_key', 'schema_value', 'updated_at'),
        category='D_runtime_temporary',
        migrate=False,
        sequence_column=None,
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('updated_at',),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason='Techniczny znacznik wersji schematu jest tworzony przez schema bootstrap targetu.',
        rebuild_procedure='Uruchom python -m app.cli.database_migrate --apply na pustym targetcie.',
        representative_fixture_required=False,
    ),
    TableMigrationSpec(
        source_table='google_calendar_oauth_states',
        target_table='google_calendar_oauth_states',
        order=None,
        primary_key=('google_calendar_oauth_state_id',),
        dependencies=('users',),
        columns=('google_calendar_oauth_state_id', 'user_id', 'state_token', 'expires_at', 'created_at'),
        category='D_runtime_temporary',
        migrate=False,
        sequence_column=None,
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('expires_at', 'created_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason='Krotkozyjace tokeny state OAuth nie moga byc przenoszone miedzy srodowiskami.',
        rebuild_procedure='Rozpocznij nowy flow OAuth; rekordy wygasaja automatycznie.',
        representative_fixture_required=False,
    ),
    TableMigrationSpec(
        source_table='system_email_oauth_states',
        target_table='system_email_oauth_states',
        order=None,
        primary_key=('system_email_oauth_state_id',),
        dependencies=('users',),
        columns=('system_email_oauth_state_id', 'state_token', 'created_by_user_id', 'login_hint', 'expires_at', 'created_at'),
        category='D_runtime_temporary',
        migrate=False,
        sequence_column=None,
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('expires_at', 'created_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason='Krotkozyjace tokeny state OAuth nie moga byc przenoszone miedzy srodowiskami.',
        rebuild_procedure='Rozpocznij nowy flow OAuth; rekordy wygasaja automatycznie.',
        representative_fixture_required=False,
    ),
    TableMigrationSpec(
        source_table='task_reminder_worker_heartbeats',
        target_table='task_reminder_worker_heartbeats',
        order=None,
        primary_key=('task_reminder_worker_heartbeat_id',),
        dependencies=(),
        columns=('task_reminder_worker_heartbeat_id', 'worker_name', 'worker_role', 'process_id', 'state', 'last_heartbeat_at', 'last_success_at', 'last_error_at', 'last_error_message', 'cycles_completed', 'processed_total', 'sent_total', 'failed_total', 'deferred_total', 'retrying_total', 'skipped_total', 'queue_total', 'queue_due', 'queue_failed', 'created_at', 'updated_at'),
        category='D_runtime_temporary',
        migrate=False,
        sequence_column=None,
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('last_heartbeat_at', 'last_success_at', 'last_error_at', 'created_at', 'updated_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason='Heartbeat opisuje konkretny proces i host, a nie trwaly stan biznesowy.',
        rebuild_procedure='Jawnie uruchomiony worker utworzy nowy heartbeat.',
        representative_fixture_required=False,
    ),
    TableMigrationSpec(
        source_table='user_sessions',
        target_table='user_sessions',
        order=None,
        primary_key=('session_id',),
        dependencies=('users',),
        columns=('session_id', 'user_id', 'token_hash', 'device_id', 'device_label', 'ip_address', 'user_agent', 'created_at', 'last_seen_at', 'expires_at'),
        category='D_runtime_temporary',
        migrate=False,
        sequence_column=None,
        json_columns=(),
        decimal_columns=(),
        boolean_columns=(),
        date_columns=(),
        timestamp_columns=('created_at', 'last_seen_at', 'expires_at'),
        blob_columns=(),
        storage_columns=(),
        exclusion_reason='Sesje i hashe tokenow sa zwiazane ze srodowiskiem i nie powinny byc przenoszone.',
        rebuild_procedure='Uzytkownicy loguja sie ponownie w nowym srodowisku.',
        representative_fixture_required=False,
    ),
)

MANIFEST_BY_TABLE = {spec.source_table: spec for spec in MIGRATION_MANIFEST}
MIGRATED_TABLES = tuple(spec for spec in MIGRATION_MANIFEST if spec.migrate)
EXCLUDED_TABLES = tuple(spec for spec in MIGRATION_MANIFEST if not spec.migrate)
TABLE_ORDER = tuple(spec.source_table for spec in MIGRATED_TABLES)
ORDER_COLUMNS = {spec.source_table: spec.primary_key[0] for spec in MIGRATED_TABLES}
POSTGRES_SEQUENCES = {
    spec.target_table: spec.sequence_column
    for spec in MIGRATED_TABLES
    if spec.sequence_column is not None
}
